# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fridge',
            field=models.ManyToManyField(related_name='item', to='pages.Fridge'),
        ),
    ]
