# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_item_fridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fridge',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruit'), ('VG', 'Veg'), ('MT', 'Meat'), ('UK', 'Unknown')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(),
        ),
    ]
