# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_item_fridge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fridge',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
    ]
